### PR TITLE
chore: require 0.15.2 of ipld-dag-pb to have name memoisation

### PR DESCRIPTION
**Pull request by achingbrain**

### CODE REVIEW

**Comment by vmx** [comment]
You might want to explicitly also upgrade to the just release ipld 0.20.2.

**Comment by achingbrain** [comment]
Do you think these should have been minors?

**Comment by vmx** [comment]
For dag-pb I'm not sure anymore. After your comment that it might lead to issues if you have two different versions installed. On the other hand, if that's a bugfix release all dependencies will automatically move to it, so it's less likely we end up with two different versions.

For js-ipld: I tested with js-ipfs and it didn't break anything, so I think it's good to go. I keep sub 1.0.0 minor releases for breaking changes and I haven't seen why anything should break.

**Comment by vmx** [comment]
So I kind of do manual pre 1.0.0 automatic seantic-release. If there is no "BREAKING CHANGE" commit, it won't be a minor.

**Comment by achingbrain** [comment]
I think we should move everything to v1, but that's another conversation.

The weird case we've encountered is that `ipld-dag-pb@0.15.2` is API compatible with `ipld-dag-pb@0.15.1` but runtime incompatible.

> all dependencies will automatically move to it

I believe this is only true if you have no `package-lock.json` present, otherwise it'll happily resolve `0.15.0` for `~0.15.0` even if `0.15.2` is available.

**Comment by vmx** [comment]
> I believe this is only true if you have no `package-lock.json` present, otherwise it'll happily resolve `0.15.0` for `~0.15.0` even if `0.15.2` is available.

Thanks for that information. So it works for CI, but not it real world.

**Review by vmx — APPROVED** [review]

**Pull request merged**
